// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mindful_Ocean_Web.server.data;

#nullable disable

namespace Mindful_Ocean_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mindful_Ocean_Web.server.model.LandingPageContent", b =>
                {
                    b.Property<int>("Content_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Content_id");

                    b.ToTable("LandingPageContents");
                });

            modelBuilder.Entity("Mindful_Ocean_Web.server.model.OceanDepth", b =>
                {
                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("Longitude", "Latitude");

                    b.ToTable("OceanDepths");
                });

            modelBuilder.Entity("Mindful_Ocean_Web.server.model.PlasticWaste", b =>
                {
                    b.Property<string>("Entity")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<double?>("Plastic_Waste")
                        .HasColumnType("double");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Entity");

                    b.ToTable("PlasticWaste");
                });
#pragma warning restore 612, 618
        }
    }
}
