name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - "server/**"
      - ".github/workflows/backend-ci.yml"

  pull_request:
    branches: [ main, develop ]
    paths:
      - "server/**"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.x"

      - name: Restore dependencies
        run: dotnet restore MindfulOcean.sln

      - name: Build
        run: dotnet build MindfulOcean.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test MindfulOcean.sln --no-build --configuration Release